/** The org-admin area as a single module. See `admin.ts` for why. */
export { default as OrgOverview } from '@/pages/org/overview'
export { default as OrgCameras } from '@/pages/org/cameras'
export { default as OrgCamerasConnect } from '@/pages/org/cameras/connect'
export { default as OrgModules } from '@/pages/org/modules'
export { default as OrgAlerts } from '@/pages/org/alerts'
export { default as OrgAlertDetail } from '@/pages/org/alerts/detail'
export { default as OrgHistory } from '@/pages/org/history'
export { default as OrgUsers } from '@/pages/org/users'
export { default as OrgRoleBuilder } from '@/pages/org/users/role-builder'
export { default as OrgAnalytics } from '@/pages/org/analytics'
export { default as OrgBilling } from '@/pages/org/billing'
export { default as OrgSettings } from '@/pages/org/settings'
export { default as OrgNotifications } from '@/pages/org/settings/notifications'
export { default as OrgProfile } from '@/pages/org/settings/profile'
export { default as OrgSecurity } from '@/pages/org/settings/security'
export { default as OrgZones } from '@/pages/org/settings/zones'
export { default as OrgAuditLog } from '@/pages/org/audit-log'
